import { jsPDF } from 'jspdf';
import { accreditationDb } from '../firebase-admin';
import { AuditService } from './audit-service';

export interface InterviewResponse {
  question: string;
  answer: string;
}

export const DocDraftingService = {
  /**
   * Synthesize a Risk Assessment PDF from structured interview responses
   */
  async generateRiskAssessment(
    userId: string,
    appId: string,
    responses: InterviewResponse[]
  ): Promise<{ pdfBuffer: Buffer; docId: string }> {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();

    // -- Header Section --
    doc.setFontSize(22);
    doc.setTextColor(40, 116, 240); // Suite Blue
    doc.text('Online Safety Risk Assessment', 20, 25);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by PromptAccreditation Policy Specialist`, 20, 32);
    doc.text(`Date: ${timestamp}`, 20, 37);
    doc.text(`Target Application: ${appId}`, 140, 37);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 42, 190, 42);

    // -- Content Section --
    let yPos = 55;
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text('1. Executive Findings', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const introText = "This document represents a self-directed risk assessment as required under the Online Safety Act 2023. The findings below are based on developer-attested configurations and operational models.";
    const splitIntro = doc.splitTextToSize(introText, 170);
    doc.text(splitIntro, 20, yPos);
    yPos += 20;

    // -- Loop through AI Interrogation Responses --
    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    doc.text('2. Interrogation Data', 20, yPos);
    yPos += 12;

    for (const item of responses) {
      // Question (Bold-ish)
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(80, 80, 80);
      const qLines = doc.splitTextToSize(`Q: ${item.question}`, 170);
      doc.text(qLines, 20, yPos);
      yPos += (qLines.length * 5) + 2;

      // Answer
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const aLines = doc.splitTextToSize(item.answer, 170);
      doc.text(aLines, 25, yPos);
      yPos += (aLines.length * 5) + 10;

      // New Page check
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
    }

    // -- Footer --
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Accreditation Safe · Document ID: ${Math.random().toString(36).substring(7).toUpperCase()}`, 20, 285);
        doc.text(`Page ${i} of ${pageCount}`, 180, 285);
    }

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const docId = `RA_${Date.now()}`;

    // For now, we store the metadata in Firestore. 
    // In a real prod environment, the buffer would go to Firebase Storage.
    await accreditationDb.collection('drafted_documents').doc(docId).set({
      type: 'risk_assessment',
      userId,
      appId,
      responses,
      createdAt: new Date(),
      status: 'generated'
    });

    await AuditService.log({
      action: 'document_drafted',
      actor: userId,
      targetType: 'check',
      targetId: 'online-safety-act',
      details: { docId, docType: 'risk_assessment' }
    });

    return { pdfBuffer, docId };
  }
};
